# Configuration:
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1
MAINTAINER Victor
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml