version: '3.3'
services:
  # Start of Elasticsearch
  elasticsearchtest:
    build: ./docker/elasticsearch
    container_name: elasticsearchtest
    environment:
    - cluster.name=next
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "discovery.seed_hosts=elasticsearchtest,elasticsearch2test"
    - "cluster.initial_master_nodes=elasticsearchtest,elasticsearch2test"
    - "node.name=elasticsearchtest"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 59200:9200
    - 59300:9300
    networks:
    - esnettest
  elasticsearch2test:
    build: ./docker/elasticsearch
    container_name: elasticsearch2test
    environment:
    - cluster.name=next
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "discovery.seed_hosts=elasticsearchtest,elasticsearch2test"
    - "cluster.initial_master_nodes=elasticsearchtest,elasticsearch2test"
    - "node.name=elasticsearch2test"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
    - esnettest
  #End of Elasticsearch

networks:
  esnettest: